// This file is automatically generated. Do not edit.
export const firebaseConfig = {
  projectId: "clarity-hub-r1yud",
  appId: "1:595661818117:web:f63fae42020b083f048f6c",
  apiKey: "AIzaSyD8bljUG9qpI5VG0Lvh6YCEIbsODuTI9AQ",
  authDomain: "clarity-hub-r1yud.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "595661818117",
  storageBucket: "clarity-hub-r1yud.appspot.com"
};
